services/app/apps/codebattle/lib/codebattle_web/router.ex
defmodule CodebattleWeb.Router do
  use CodebattleWeb, :router
  use Plug.ErrorHandler

  import Phoenix.LiveDashboard.Router

  require Logger

  pipeline :admins_only do
    plug(CodebattleWeb.Plugs.AssignCurrentUser)
    plug(CodebattleWeb.Plugs.AdminOnly)
  end

  pipeline :require_auth do
    plug(CodebattleWeb.Plugs.RequireAuth)
  end

  pipeline :require_api_auth do
    plug(CodebattleWeb.Plugs.ApiRequireAuth)
  end

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:fetch_live_flash)
    plug(CodebattleWeb.Plugs.AssignCurrentUser)
    plug(CodebattleWeb.Plugs.ForceRedirect)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(PhoenixGon.Pipeline)
    plug(CodebattleWeb.Plugs.AssignGon)
    plug(CodebattleWeb.Plugs.Locale)
  end

  pipeline :empty_layout do
    plug(:put_layout, {CodebattleWeb.LayoutView, :empty})
  end

  pipeline :api do
    plug(:accepts, ["json"])
    plug(:fetch_session)
    plug(CodebattleWeb.Plugs.AssignCurrentUser)
    plug(CodebattleWeb.Plugs.ForceRedirect)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :ext_api do
    plug(:accepts, ["json"])
    plug(:put_secure_browser_headers)
  end

  pipeline :public_api do
    plug(:accepts, ["json"])
  end

  pipeline :mounted_apps do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:put_secure_browser_headers)
  end

  scope "/ext_api", CodebattleWeb.ExtApi, as: :ext_api do
    pipe_through([:ext_api])
    post("/execute", ExecutorController, :execute)
    post("/users", UserController, :create)
  end

  scope "/", CodebattleWeb do
    get("/health", HealthController, :index)
  end

  scope "/admin" do
    pipe_through([:browser, :admins_only])
    live_dashboard("/dashboard", metrics: CodebattleWeb.Telemetry)
    live("/users", CodebattleWeb.Live.Admin.User.IndexView, :index)
  end

  scope "/auth", CodebattleWeb do
    pipe_through(:browser)
    get("/token", AuthController, :token)
    post("/dev_login", DevLoginController, :create)
    get("/:provider", AuthController, :request)
    get("/:provider/callback", AuthController, :callback)

    # for binding
    get("/:provider/bind", AuthBindController, :request)
    get("/:provider/callback/bind", AuthBindController, :callback)
    delete("/:provider", AuthBindController, :unbind)
  end

  scope "/public_api", CodebattleWeb.Api, as: :api do
    pipe_through(:public_api)

    scope "/v1", V1, as: :v1 do
      get("/events/:id/leaderboard", Event.LeaderboardController, :show)
    end
  end

  scope "/api", CodebattleWeb.Api, as: :api do
    pipe_through(:api)

    scope "/v1", V1, as: :v1 do
      scope("/games") do
        get("/completed", GameController, :completed)
      end

      get("/:user_id/activity", ActivityController, :show)
      get("/game_activity", GameActivityController, :show)
      get("/playbook/:id", PlaybookController, :show)
      get("/user/:id/stats", UserController, :stats)
      get("/user/:id/simple_stats", UserController, :simple_stats)
      get("/user/premium_requests", UserController, :premium_requests)
      post("/user/:id/send_premium_request", UserController, :send_premium_request)
      get("/user/current", UserController, :current)
      resources("/reset_password", ResetPasswordController, only: [:create], singleton: true)
      resources("/session", SessionController, only: [:create], singleton: true)
      resources("/settings", SettingsController, only: [:show, :update], singleton: true)
      resources("/tasks", TaskController)
      post("/tasks/build", TaskController, :build)
      post("/tasks/check", TaskController, :check)
      get("/tasks/:name/unique", TaskController, :unique)
      resources("/users", UserController, only: [:index, :show, :create])
      post("/playbooks/approve", PlaybookController, :approve)
      post("/playbooks/reject", PlaybookController, :reject)
      get("/events/:id/leaderboard", Event.LeaderboardController, :show)
    end

    scope "/v1", V1, as: :v1 do
      pipe_through(:require_api_auth)

      resources("/feedback", FeedbackController, only: [:index, :create])
      get("/:user_id/activity", ActivityController, :show)

      scope("/games") do
        resources("/:id/user_game_reports", UserGameReportController, only: [:create])
      end
    end
  end

  scope "/", CodebattleWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/robots.txt", RootController, :robots)
    get("/sitemap.xml", RootController, :sitemap)
    get("/feedback/rss.xml", RootController, :feedback)

    get("/", RootController, :index)

    resources("/session", SessionController, singleton: true, only: [:delete, :new])
    get("/remind_password", SessionController, :remind_password)

    resources("/tournaments", TournamentController, only: [:index, :show])

    scope "/tournaments" do
      get("/:id/admin", Tournament.AdminController, :show)
      get("/:id/image", Tournament.ImageController, :show, as: :tournament_image)
      get("/:id/player/:player_id", Tournament.PlayerController, :show, as: :tournament_player)
    end

    scope "/tournaments" do
      pipe_through(:empty_layout)
      get("/:id/timer", LiveViewTournamentController, :show_timer, as: :tournament_timer)
    end

    get("/clans/", ClanController, :index)
    get("/clans/:id", ClanController, :show)

    resources("/events", EventController)
    get("/e/:slug", PublicEventController, :show)

    resources("/users", UserController, only: [:new])
    resources("/feedback", FeedbackController, only: [:index])

    resources("/games", GameController, only: [:show]) do
      get("/image", Game.ImageController, :show, as: :image)
    end

    scope "/games" do
      post("/training", GameController, :create_training)
    end
  end

  scope "/", CodebattleWeb do
    pipe_through([:browser, :require_auth])

    resources("/users", UserController, only: [:index, :show])
    get("/settings", UserController, :edit, as: :user_setting)

    resources("/task_packs", TaskPackController) do
      patch("/activate", TaskPackController, :activate, as: :activate)
      patch("/disable", TaskPackController, :disable, as: :disable)
    end

    resources("/tasks", TaskController) do
      patch("/activate", TaskController, :activate, as: :activate)
      patch("/disable", TaskController, :disable, as: :disable)
    end

    resources("/games", GameController, only: [:delete])

    scope "/games" do
      post("/:id/join", GameController, :join)
    end

    # only for dev-admin liveView experiments
    resources("/live_view_tournaments", LiveViewTournamentController,
      only: [:index, :show, :edit]
    )
  end

  scope "/feature-flags" do
    pipe_through([:mounted_apps, :admins_only])
    forward("/", FunWithFlags.UI.Router, namespace: "feature-flags")
  end

  def handle_errors(conn, %{reason: %Ecto.NoResultsError{}}) do
    conn
    |> put_status(:not_found)
    |> json(%{error: "NOT_FOUND"})
    |> halt
  end

  def handle_errors(conn, %{reason: %Phoenix.Router.NoRouteError{}}) do
    conn
    |> put_status(:not_found)
    |> json(%{error: "NOT_FOUND"})
    |> halt
  end

  def handle_errors(conn, %{kind: _kind, reason: reason}) do
    Logger.error(inspect(reason))
    send_resp(conn, conn.status, "SOMETHING_WENT_WRONG, reason: #{inspect(reason)}")
  end
end

services/app/apps/codebattle/lib/codebattle_web/controllers/api/v1/event/leaderboard_controller.ex
defmodule CodebattleWeb.Api.V1.Event.LeaderboardController do
  use CodebattleWeb, :controller

  alias Codebattle.Repo
  alias Codebattle.Clan.Scope
  alias Codebattle.Event.EventClanResult
  alias Codebattle.Event.EventResult
  @page_size 10

  def show(conn, params) do
    page_number =
      case Map.get(params, "page_number") do
        nil -> nil
        "" -> nil
        page -> page |> cast_int() |> min(2000)
      end

    page_size = params |> Map.get("page_size") |> cast_int(@page_size) |> min(20)
    event_id = params |> Map.get("id") |> cast_int(1)
    clan_id = cast_int(params["clan_id"], 1)
    user_id = cast_int(params["user_id"], 1)

    response =
      case Map.get(params, "type", "clan") do
        # rating for all clans without players
        # %{"clan_id" => clan_id} ->
        "clan" ->
          get_by_clan(event_id, clan_id, page_size, page_number)

        # rating for players in all clans
        # %{"user_id" => user_id} ->
        "player" ->
          get_by_player(event_id, user_id, page_size, page_number)

        # rating for players only inside users clan
        "player_clan" ->
          # %{"user_id" => user_id, "clan_id" => clan_id} ->
          get_by_clan_palyer(event_id, clan_id, user_id, page_size, page_number)

        _ ->
          %{
            items: [],
            page_info: %{page_number: 0, page_size: 0, total_entries: 0, total_pages: 0}
          }
      end

    json(conn, response)
  end

  defp get_by_clan(event_id, clan_id, page_size, page_number) do
    result =
      event_id
      |> EventClanResult.get_by_clan_id(clan_id, page_size, page_number)
      |> case do
        result = %{entries: [_ | _]} ->
          result

        _ ->
          default_page_number = cast_int(page_number, 1)

          Scope.by_clan()
          |> Repo.paginate(%{page: default_page_number, page_size: page_size, total: true})
      end

    page_info = Map.take(result, [:page_number, :page_size, :total_entries, :total_pages])

    %{
      clan_id: clan_id,
      items: result.entries,
      page_info: page_info
    }
  end

  defp get_by_player(event_id, user_id, page_size, page_number) do
    result =
      event_id
      |> EventResult.get_by_user_id(user_id, page_size, page_number)
      |> case do
        result = %{entries: [_ | _]} ->
          result

        _ ->
          default_page_number = cast_int(page_number, 1)

          Scope.by_player()
          |> Repo.paginate(%{page: default_page_number, page_size: page_size, total: true})
      end

    page_info = Map.take(result, [:page_number, :page_size, :total_entries, :total_pages])

    %{
      user_id: user_id,
      items: result.entries,
      page_info: page_info
    }
  end

  defp get_by_clan_palyer(event_id, clan_id, user_id, page_size, page_number) do
    result =
      event_id
      |> EventResult.get_by_user_id_and_clan_id(user_id, clan_id, page_size, page_number)
      |> case do
        result = %{entries: [_ | _]} ->
          result

        _ ->
          default_page_number = cast_int(page_number, 1)

          clan_id
          |> Scope.by_player_clan()
          |> Repo.paginate(%{page: default_page_number, page_size: page_size, total: true})
      end

    page_info = Map.take(result, [:page_number, :page_size, :total_entries, :total_pages])

    %{
      clan_id: clan_id,
      user_id: user_id,
      items: result.entries,
      page_info: page_info
    }
  end

  defp cast_int(value, default \\ nil)
  defp cast_int(nil, default), do: default
  defp cast_int("", default), do: default
  defp cast_int(int, _default) when is_integer(int), do: int

  defp cast_int(str, default) when is_binary(str) do
    String.to_integer(str)
  rescue
    _e -> default || 1
  end

  defp cast_int(_, default), do: default
end

services/app/apps/codebattle/lib/codebattle_web/controllers/event_controller.ex
defmodule CodebattleWeb.EventController do
  use CodebattleWeb, :controller

  plug CodebattleWeb.Plugs.AdminOnly

  alias Codebattle.Event

  def index(conn, _params) do
    conn
    |> put_meta_tags(%{title: "Codebattle Events"})
    |> render("index.html", %{events: Event.get_all(), user: conn.assigns.current_user})
  end

  def new(conn, _params) do
    conn
    |> put_meta_tags(%{title: "Codebattle Event"})
    |> render("new.html",
      changeset: Codebattle.Event.changeset(%Codebattle.Event{}),
      user: conn.assigns.current_user
    )
  end

  def show(conn, %{"id" => id}) do
    event = Event.get!(id)

    conn
    |> put_meta_tags(%{title: event.title})
    |> render("show.html", %{event: event, user: conn.assigns.current_user})
  end

  def create(conn, %{"event" => event_params}) do
    user = conn.assigns.current_user
    params = Map.put(event_params, "user_id", user.id)

    case Codebattle.Event.create(params) do
      {:ok, event} ->
        conn
        |> put_flash(:info, "Event created successfully.")
        |> redirect(to: Routes.event_path(conn, :show, event))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset, user: user)
    end
  end

  def update(conn, %{"id" => id, "event" => event_params}) do
    event = Event.get!(id)

    case Codebattle.Event.update(
           event,
           Map.put(event_params, "user_id", conn.assigns.current_user.id)
         ) do
      {:ok, event} ->
        conn
        |> put_flash(:info, "Event updated successfully.")
        |> redirect(to: Routes.event_path(conn, :edit, event.id))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", event: event, changeset: changeset)
    end
  end

  def edit(conn, %{"id" => id}) do
    event = Event.get!(id)

    changeset = Codebattle.Event.changeset(event)
    render(conn, "edit.html", event: event, changeset: changeset, user: conn.assigns.current_user)
  end

  def delete(conn, %{"id" => id}) do
    event = Event.get!(id)

    Event.delete(event)

    conn
    |> put_flash(:info, gettext("Event deleted!"))
    |> redirect(to: Routes.event_path(conn, :index))
  end
end

services/app/apps/codebattle/lib/codebattle_web/live/event/leaderboard_view.ex
defmodule CodebattleWeb.Live.Event.LeaderboardView do
  use CodebattleWeb, :live_view

  # require Logger
  import CodebattleWeb.Gettext

  @impl true
  def mount(_params, session, socket) do
    {:ok,
     assign(socket,
       current_user: session["current_user"],
       leaderboard_list: session["leaderboard"]
     )}
  end

  @impl true
  def render(assigns) do
    ~H"""
    <div class="d-flex w-100 px-1 bg-white">
      <table class="table table-striped cb-custom-event-table">
        <thead class="sticky-top text-muted bg-white">
          <tr>
            <th class="p-1 pl-4 font-weight-light border-0"><%= gettext("Place") %></th>
            <th class="p-1 pl-4 font-weight-light border-0"><%= gettext("Score") %></th>
            <th class="p-1 pl-4 font-weight-light border-0"><%= gettext("Clan players count") %></th>
            <th class="p-1 pl-4 font-weight-light border-0"><%= gettext("Clan") %></th>
          </tr>
        </thead>
        <tbody>
          <%= for item <- @leaderboard_list do %>
            <tr class="cb-custom-event-empty-space-tr"></tr>
            <tr class="text-dark font-weight-bold cb-custom-event-tr bg-light">
              <td class="p-1 pl-4 my-2 align-middle text-nowrap position-relative cb-custom-event-td border-0">
                <%= item.place %>
              </td>
              <td class="p-1 pl-4 my-2 align-middle text-nowrap position-relative cb-custom-event-td border-0">
                <%= item.score %>
              </td>
              <td class="p-1 pl-4 my-2 align-middle text-nowrap position-relative cb-custom-event-td border-0">
                <%= item.players_count %>
              </td>
              <td class="p-1 pl-4 my-2 align-middle text-nowrap position-relative cb-custom-event-td border-0">
                <%= item.clan_name %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    """
  end
end

services/app/apps/codebattle/lib/codebattle_web/views/event_view.ex
defmodule CodebattleWeb.EventView do
  use CodebattleWeb, :view

  def format_datetime(d, tz \\ "UTC")
  def format_datetime(nil, _time_zone), do: "none"

  def format_datetime(datetime = %NaiveDateTime{}, timezone) do
    datetime
    |> DateTime.from_naive!("UTC")
    |> format_datetime(timezone)
  end

  def format_datetime(datetime = %DateTime{}, timezone) do
    datetime
    |> DateTime.shift_zone!(timezone)
    |> Timex.format!("%Y-%m-%d %H:%M %Z", :strftime)
  end
end

services/app/apps/codebattle/lib/codebattle_web/templates/event/_form.html.heex
<%= f = form_for(@changeset, @action, class: "col-8  offset-2") %>
<div class="form-group">
  <div>
    <span>Slug</span>
    <span class="ml-3 text-muted">Slug for an Event should be unique</span>
  </div>
  <%= text_input(f, :slug,
    class: "form-control form-control-lg",
    maxlength: "57",
    required: false
  ) %>
  <%= error_tag(f, :slug) %>
</div>
<div class="form-group">
  <div>
    <span>Title</span>
  </div>
  <%= text_input(f, :title,
    class: "form-control form-control-lg",
    maxlength: "157",
    required: false
  ) %>
  <%= error_tag(f, :title) %>
</div>
<div class="form-group">
  <div>
    <span>Description</span>
  </div>
  <%= textarea(f, :description, class: "form-control form-control-lg") %>
  <%= error_tag(f, :description) %>
</div>
<div class="form-group">
  <%= label(f, :type) %>
  <%= select(f, :type, Codebattle.Event.types(), class: "form-control form-control-lg") %>
  <%= error_tag(f, :type) %>
</div>
<div class="d-flex flex-column justify-content-between w-auto">
  <label>Starts at (<%= @user.timezone %>)</label>
  <%= datetime_local_input(f, :starts_at,
    class: "form-control",
    required: true,
    value: f.params["starts_at"] || DateTime.add(DateTime.now!(@user.timezone), 5, :minute)
  ) %>
  <%= error_tag(f, :starts_at) %>
</div>
<div class="d-flex">
  <%= submit("Save",
    phx_disable_with: "Saving...",
    class: "btn btn-success text-white mb-2 rounded-lg"
  ) %>
  <%= link("Back", to: Routes.task_pack_path(@conn, :index), class: "btn btn-link ml-auto") %>
</div>

services/app/apps/codebattle/lib/codebattle_web/templates/event/edit.html.heex
<div class="container-xl bg-white shadow-sm rounded py-4 mb-3">
  <h1 class="text-center">Edit Event</h1>
  <%= render("_form.html", Map.put(assigns, :action, Routes.event_path(@conn, :create))) %>
</div>

services/app/apps/codebattle/lib/codebattle_web/templates/event/index.html.heex
<div class="container-xl bg-white shadow-sm rounded py-4 mb-3">
  <h1 class="text-center">Events</h1>
  <%= link("Create new event",
    to: Routes.event_path(@conn, :new),
    class: "btn btn-success text-white mt-2 rounded-lg"
  ) %>
  <div class="table-responsive mt-4">
    <table class="table table-sm">
      <thead>
        <tr>
          <th>slug</th>
          <th>type</th>
          <th>title</th>
          <th>starts_at</th>
          <th>description</th>
        </tr>
      </thead>
      <tbody>
        <%= for event <- @events do %>
          <tr>
            <td class="align-middle text"><%= event.slug %></td>
            <td class="align-middle text"><%= event.type %></td>
            <td class="align-middle text"><%= event.title %></td>
            <td class="align-middle text"><%= format_datetime(event.starts_at) %></td>
            <td class="align-middle text">
              <%= event.description && String.slice(event.description, 1..10) %>
            </td>
            <td class="align-middle text-nowrap">
              <div class="d-flex">
                <%= link("Show",
                  to: Routes.event_path(@conn, :show, event.id),
                  class: "btn btn-sm btn-info rounded-lg"
                ) %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

services/app/apps/codebattle/lib/codebattle_web/templates/event/new.html.heex
<div class="container-xl bg-white shadow-sm rounded py-4 mb-3">
  <h1 class="text-center">Create Event</h1>
  <%= render("_form.html", Map.put(assigns, :action, Routes.event_path(@conn, :create))) %>
</div>

services/app/apps/codebattle/lib/codebattle_web/templates/event/show.html.heex
<div class="container-xl bg-white shadow-sm rounded py-4 mb-3">
  <h1 class="text-center">
    <span><%= @event.title %></span>
  </h1>
  <h3 class="text-center mt-4">Params</h3>
  <div class="d-flex flex-wrap align-items-center justify-content-around text-muted">
    <span>Type: <%= @event.type %></span>
    <span>Title: <%= @event.title %></span>
    <span>Description: <%= @event.description %></span>
    <span>Creator_id: <%= @event.creator_id %></span>
  </div>

  <%= link("Back", to: Routes.event_path(@conn, :index), class: "ml-auto") %>
</div>